Created web project
michal-tracichleb/QuirkyCarRepair pull request #5
Opened 2023-10-27 12:39 UTC by Oskii0201

2023-10-27 12:56 UTC, michal-tracichleb requested changes
Dodałem komentarze

2023-10-27 12:56 UTC, michal-tracichleb commented on quirky-car-repair/src/NavBar.js
Plik przeniósłbym do katalogu quirky-car-repair/views/components  nawet równoległy do Src katalog.
w SRC trzymałbym tylko logikę biznesową - łączenie z API, servisy, middlware, routing kontrolery (o ile będą)

2023-10-27 12:56 UTC, michal-tracichleb commented on quirky-car-repair/public/index.html
W katalogu public trzymamy elementy które udostępniamy "światu", jak katalog z stylami css/style.css, katalog z udostępnionymi obrazami img/logo_1.bmp.
index.html do katalogu quirky-car-repair/views/pages/index.html

2023-10-27 12:56 UTC, michal-tracichleb commented on quirky-car-repair/src/App.css
style css trzymałbym w folderze quirky-car-repair/public/css/App.css

2023-10-27 12:56 UTC, michal-tracichleb commented on quirky-car-repair/public/index.html
> +
Może warto tutaj zaimplementować (jako footer) .js z Bootstrapa i wykorzystać index.html jako layout? 
A w  headzie stylowanie?

2023-10-28 23:03 UTC, mbor357 approved these changes

2023-11-04 16:17 UTC, michal-tracichleb approved these changes

2023-11-04 16:32 UTC, merged